apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30000

# Note: Once everything is up and running, you can do the following:
# 1: Got to: http: // <youNodeIp>: 30000 and you will be taken to the Prometheus landing page.
# Thanks to the job defined in config.yaml in this directory, - job_name: 'kube-state-metrics'.
# 2: We can view all the static metrics  provided by the Kube state by going to: http: // <youNodeIp>: 30000 / metrics
#