apiVersion: v1
kind: Pod
metadata:
      name: tomcat-pod
      labels:
        distro: linux
spec:
  containers:
    - name: tomcat-container
      image: tomcat
      resources:
        limits:
          cpu: "402m" 
          memory: "300Mi"
#requests must be < limits
        requests:
          cpu: "400m"
          memory:  "300Mi"