apiVersion: v1
kind: Pod
metadata:
      name: busy-panda
      labels:
        animal: wild
      namespace: pivot
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ["sleep", "86400"]
      resources:
        limits:
          cpu: "238m" 
          memory: "333Mi"
#Request musbe < than limit otherwise an error is thrown          
        requests:
          cpu: "215m"
          memory:  "220Mi"
---
# This tenant will not be scheduled as it breaks the namespace Quota, the minimum cpu request!
apiVersion: v1
kind: Pod
metadata:
      name: dead-shark
      labels:
        scary: shark
spec:
  containers:
    - name: dead-shark-container
      image: coolgourav147/nginx-custom
      resources:
       limits:
         cpu: "500m" 
         memory: "400Mi"
       requests:
         cpu: "205m" # deliberately assinging a breaking value
         memory: "185Mi"
---
# This tenant will not be scheduled as it breaks the namespace Quota, the maximum memory request!
apiVersion: v1
kind: Pod
metadata:
      name: dancing-peacock
      labels:
        animal: colorful
spec:
  containers:
    - name: dancing-peacock-container
      image: coolgourav147/nginx-custom
      resources:
       limits:
         cpu: "400m" 
         memory: "703Mi" # deliberately assinging a breaking value
       requests:
         cpu: "239m" 
         memory: "199Mi"