apiVersion:  v1
kind: LimitRange
metadata:
  name: ns-pivot-limit-range
  namespace: pivot
spec:
  limits:
    - 
#Default Limit
      type: "Container" 
      default:
        cpu: "300m" 
        memory: "300Mi"
#Default Request must be < than Default Limit
      defaultRequest:
        cpu: "220m"
        memory: "250Mi"
# Max and Min CPU and RAM allowed per container when defined by a developer
      max: 
      #This must be > defualt Limit and defaultRequest, as if it is < default then it will not work
        cpu: "1002m"  
        memory: "700Mi"
      #This must be < defualt Limit and defaultRequest, as if it is > default then it will not work
      min:
        cpu: "210m"
        memory: "180Mi"

# The aggregated resources overview of the namespace *pivot*
 
  #   limits.cpu: "2100m"
  #   limits.memory: 1900Mi
  #   requests.cpu: "2100m" 
  #   requests.memory: 1900Mi
  #   pods: "10"
  #   replicationcontrollers: "3"
  #   resourcequotas: "1"
  #   configmaps: "4"
  #   services: "4"